apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-vijay
  labels:
    app: hello-vijay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-vijay
  template:
    metadata:
      labels:
        app: hello-vijay
    spec:
      containers:
      - name: hello-vijay
        image: vijaybtw07/hello-vijay:latest
        ports:
        - containerPort: 80
